# Generated by Django 4.0.4 on 2022-05-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about_clients_strategy_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
    ]
