# Generated by Django 4.0.4 on 2022-05-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(blank=True, max_length=60)),
                ('client', models.CharField(max_length=50)),
                ('launched', models.CharField(max_length=50)),
                ('demands', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=255)),
                ('short_detail', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('slug', models.SlugField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='home.service')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('-created',),
            },
        ),
    ]
