# Generated by Django 4.0.4 on 2022-05-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about_clients_strategy_team'),
        ('project', '0002_images_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.service'),
        ),
    ]
